<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Programa;

class ProgramaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $programas = [
            [
                'Codigo_Programa' => 4021,
                'Nombre_Programa' => 'Ingeniería Civil', 
                'Codigo_SNIES' => '4121',
                'Url_Programa' => 'https://fia.unal.edu.co/index.php?option=com_content&view=article&id=254&Itemid=117',
                'Codigo_Facultad' => 4036,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 179,
                'Campus_Programa' => 'Campus Palogrande',
                'Conmutador' => '8879300',
                'Extension' => '50125 - 50126',
                'Correo' => 'cingci_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4025,
                'Nombre_Programa' => 'Arquitectura y Urbanismo', 
                'Codigo_SNIES' => '4126',
                'Url_Programa' => 'https://fia.unal.edu.co/index.php?option=com_content&view=article&id=250&Itemid=117',
                'Codigo_Facultad' => 4036,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 168,
                'Campus_Programa' => 'Campus El Cable',
                'Conmutador' => '8879300',
                'Extension' => '51115 - 51102 - 51103',
                'Correo' => 'carqui_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4022,
                'Nombre_Programa' => 'Ingeniería Eléctrica', 
                'Codigo_SNIES' => '4122',
                'Url_Programa' => 'https://fia.unal.edu.co/index.php?option=com_content&view=article&id=252&Itemid=117',
                'Codigo_Facultad' => 4036,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 164,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '55718 - 55719 - 55720',
                'Correo' => 'cingelca_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4028,
                'Nombre_Programa' => 'Ingeniería Electrónica', 
                'Codigo_SNIES' => '4123',
                'Url_Programa' => 'https://fia.unal.edu.co/index.php?option=com_content&view=article&id=253&Itemid=117',
                'Codigo_Facultad' => 4036,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 161,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '55718 - 55719 - 55720',
                'Correo' => 'seciee_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4024,
                'Nombre_Programa' => 'Ingeniería Industrial', 
                'Codigo_SNIES' => '4124',
                'Url_Programa' => 'https://fia.unal.edu.co/index.php?option=com_content&view=article&id=251&Itemid=117',
                'Codigo_Facultad' => 4036,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 169,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '55782',
                'Correo' => 'cingin_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4023,
                'Nombre_Programa' => 'Ingeniería Química', 
                'Codigo_SNIES' => '4125',
                'Url_Programa' => 'https://fia.unal.edu.co/index.php?option=com_content&view=article&id=254&Itemid=117',
                'Codigo_Facultad' => 4036,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 180,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '55111 - 55112',
                'Correo' => 'cingqu_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4026,
                'Nombre_Programa' => 'Administración de Empresas Diurno', 
                'Codigo_SNIES' => '4120',
                'Url_Programa' => '',
                'Codigo_Facultad' => 4046,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 0,
                'Campus_Programa' => 'Campus Palogrande',
                'Conmutador' => '8879300',
                'Extension' => '',
                'Correo' => 'caradmon_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4027,
                'Nombre_Programa' => 'Administración de Empresas Nocturno', 
                'Codigo_SNIES' => '16911',
                'Url_Programa' => '',
                'Codigo_Facultad' => 4046,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 0,
                'Campus_Programa' => 'Campus Palogrande',
                'Conmutador' => '8879300',
                'Extension' => '',
                'Correo' => 'caradmon_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4035,
                'Nombre_Programa' => 'Administración de Sistemas Informáticos', 
                'Codigo_SNIES' => '16912',
                'Url_Programa' => '',
                'Codigo_Facultad' => 4046,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 0,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '',
                'Correo' => 'admonsis_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4033,
                'Nombre_Programa' => 'Gestión Cultural y Comunicativa',
                'Codigo_SNIES' => '16914',
                'Url_Programa' => '',
                'Codigo_Facultad' => 4191,
                'Duracion_Semestres' => 9,
                'Creditos_Totales' => 0,
                'Campus_Programa' => 'Campus Palogrande',
                'Conmutador' => '8879300',
                'Extension' => '',
                'Correo' => 'cgescul_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4030,
                'Nombre_Programa' => 'Ingeniería Física',
                'Codigo_SNIES' => '16915',
                'Url_Programa' => '',
                'Codigo_Facultad' => 4037,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 170,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '',
                'Correo' => 'caringfis_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4032,
                'Nombre_Programa' => 'Matemáticas',
                'Codigo_SNIES' => '16916',
                'Url_Programa' => '',
                'Codigo_Facultad' => 4037,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 140,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '',
                'Correo' => 'carmate_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4034,
                'Nombre_Programa' => 'Ciencias de la Computación',
                'Codigo_SNIES' => '110177',
                'Url_Programa' => '',
                'Codigo_Facultad' => 4037,
                'Duracion_Semestres' => 9,
                'Creditos_Totales' => 143,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '',
                'Correo' => 'carcomp_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4036,
                'Nombre_Programa' => 'Estadística',
                'Codigo_SNIES' => '116559',
                'Url_Programa' => '',
                'Codigo_Facultad' => 4037,
                'Duracion_Semestres' => 9,
                'Creditos_Totales' => 151,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '',
                'Correo' => 'carmate_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
            [
                'Codigo_Programa' => 4037,
                'Nombre_Programa' => 'Ingeniería Biológica',
                'Codigo_SNIES' => '116558',
                'Url_Programa' => '',
                'Codigo_Facultad' => 4037,
                'Duracion_Semestres' => 10,
                'Creditos_Totales' => 168,
                'Campus_Programa' => 'Campus La Nubia',
                'Conmutador' => '8879300',
                'Extension' => '',
                'Correo' => 'caringfis_man@unal.edu.co',
                'Esta_Activo' => 1,
            ],
        ];

        foreach ($programas as $programa) {
            Programa::create([
                'Codigo_Facultad' => $programa['Codigo_Facultad'],
                'Codigo_Programa' => $programa['Codigo_Programa'],
                'Nombre_Programa' => $programa['Nombre_Programa'],
                'Creditos_Totales' => $programa['Creditos_Totales'],
                'Duracion_Semestres' => $programa['Duracion_Semestres'],
                'Codigo_SNIES' => $programa['Codigo_SNIES'],
                'Url_Programa' => $programa['Url_Programa'],
                'Campus_Programa' => $programa['Campus_Programa'],
                'Conmutador' => $programa['Conmutador'],
                'Extension' => $programa['Extension'],
                'Correo' => $programa['Correo'],
                'Esta_Activo' => $programa['Esta_Activo'],
            ]);
        }
    }
}

